server {
  listen 5500;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location ^~ /The-Heallthy-Lab/ {
    rewrite ^/The-Heallthy-Lab/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(css|js|jpg|jpeg|gif|png|svg|ico|webp|avif|woff|woff2)$ {
    # Caching disabled for active development
    add_header Cache-Control "no-store, no-cache, must-revalidate";
    try_files $uri =404;
  }
}
